---

title: "The Politics of the Incarcerated"
output: html_document
date: "2025-3-6"
---

<style>
  .color{
  color:#9d3525;
}
</style>

<h1 class="color">The Politics</h1>

<p> Hello <span class="color">World</span><p>

# Load software libraries
```{r results='hide', error=F, warning=F, message=F}
#install.packages("tidyverse")
#install.packages("janitor")
#install.packages("readxl")
#install.packages("rvest")
library(tidyverse)
library(janitor)
library(readxl)
library(rvest)

```
Incarcerated individuals political opinions


By Sophia Nabours, scnabours@gmail.com, 501-593-0494, June 2, 2025

Examining the prison population’s political opinions during the 2024 election and exploring how both those who were barred and allowed to vote would have been reflected in polling data. How their collective political beliefs reveal about justice, disenfranchisement, overlooked elective narratives affected public opinion on prisoners’ potential voting choices. 
As conversations around criminal justice reform, detainee rights, and voting rights for incarcerated individuals gain traction ahead of the 2026 midterms, this piece will provide a timely lens into the political voices often most forgotten.
AUDIENCE: voters, researchers, formerly incarcerated and currently incarcerated individuals.
POSSIBLE SOURCES: 1) A data researcher from the Marshall Project that worked on the survey. 2) An incarcerated and formerly incarcerated individual willing to speak on political views in/outside prison. What is the political climate like in detainment? How were your political views affected by prison? 3) I’d love to look for a voting rights expert, someone informed on detained voting, 

https://brilliantmaps.com/if-only-x-voted/

AP-NORC Center for Public Affairs Research (March, 2025). “AP VoteCast 2024 General Election.” https://apnorc.org/projects/ap-votecast-2024-general-election


During the 2024 election, President Donald Trump reclaimed his position of power with 312 electoral college votes, beating the former Vice President Kamala Harris who received 226 electoral votes. Following the election, a large number of “what if” scenarios began to circulate. 

What if only white men had voted in the 2024 election? According to AP VoteCast 2024 general election data, Trump would have instead won by TKTK amount of votes, a TKTK increase from the general population. If only black men had voted the numbers would flip, displaying Harris polling in ahead of Trump by TKTK percentage points. 

However, the “what if” of the incarcerated population has remained untouched. Using the Marshall Project’s survey of the political stances of incarcerated individuals across the U.S., we can create an often unrecognized voting population–actively detained prisoners and inmates.  

Incarcerated population voting opinion polled in July of 2024 following the succession of Harris as the Democratic nominee: 


Alabama: 47% TRUMP, 32% HARRIS
Arkansas: 44.8% TRUMP, 33.7% HARRIS
Arizona: 37.6% TRUMP, 40.2% HARRIS
California: 37% TRUMP, 40.2% HARRIS
Colorado: 48.82% TRUMP 27.36% HARRIS
DC: 46.9% TRUMP, 30.9% HARRIS
Florida: 58.3% TRUMP, 21.3% HARRIS
Georgia: 47.2% TRUMP, 33.9% HARRIS
Iowa: 40% TRUMP, 36.4% HARRIS
Idaho: 
Illinois: 48% TRUMP, 30.7% HARRIS
Indiana: 58.67% TRUMP, 21% HARRIS
Kansas: 52% TRUMP, 29.7% HARRIS
Kentucky: 74.3% TRUMP, TKTK
Louisiana: 65.1% HARRIS, 22.3% TRUMP
Massachusetts: 47.8% TRUMP, 33.6% HARRIS
Maryland: 45.3% HARRIS, 34% TRUMP
Maine: 62% TRUMP, 22.17% HARRIS
Michigan: 50.93% TRUMP, 32.3% HARRIS
Minnesota: 53.1%
Missouri: 46.4% TRUMP, 33% HARRIS
Mississippi: 44.4% TRUMP, 36% HARRIS
Montana: 63.1% TRUMP, 20% HARRIS
North Carolina: 48.4% TRUMP, 32% HARRIS
North Dakota: 62.3% TRUMP, 24.7% HARRIS
Nebraska: 44% TRUMP, 36.9% HARRIS
New Hampshire: 47.7% TRUMP, 37.6% HARRIS
New Jersey: 43% TRUMP, 35.9% HARRIS
New Mexico: 49.4% TRUMP, 24.14% HARRIS
New York: 49.7% TRUMP, 27.3% HARRIS
Ohio: 49.7% TRUMP, 30.6% HARRIS
Oklahoma: 38.6% TRUMP, 36% HARRIS
Oregon: 46.6% TRUMP, 33.6% HARRIS
Pennsylvania: 55.2% TRUMP, 25.5% HARRIS
Rhode ISland: 59.4% TKTK
South Carolina: 50.1% TRUMP, 31.3% HARRIS
South Dakota: 38.6% HARRIS, 34%
Tennessee: 55.4% TRUMP, 29% HARRIS
Texas: 52.7% TRUMP, 27% HARRIS
Utah: 56.1% TRUMP, 19.3% HARRIS
Virginia: 48.4% TRUMP, 30.4% HARRIS
Washington: 48.4% TRUMP, 28.5% HARRIS
Wisconsin: 44.8% TRUMP, 32.9% HARRIS
West Virginia: 67.2% TRUMP, 14.1% HARRIS

Graphics/Visuals
An interactive U.S. map showing how the electoral college map would have shifted if only incarcerated people voted. 
Infographics containing information on state-by-state felony voting laws








<iframe title="[ Insert title here ]" aria-label="Map" id="datawrapper-chart-Ly7uj" src="https://datawrapper.dwcdn.net/Ly7uj/3/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="400" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r,i=0;r=e[i];i++)if(r.contentWindow===a.source){var d=a.data["datawrapper-height"][t]+"px";r.style.height=d}}}))}();
</script>

